### ISSUE TITLE
progurd error

### ISSUE THREAD

**Issue by Hoosein** [akexorcist/Android-GoogleDirectionLibrary#20]
while proguard is true

```
Process: com.kama.khajoie.sirjan118, PID: 3179
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                              at com.akexorcist.googledirection.model.Direction.b(Unknown Source)
                                                                              at com.kama.khajoie.sirjan118.Test.a(Unknown Source)
                                                                              at com.akexorcist.googledirection.b.d.a(Unknown Source)
                                                                              at c.u.run(Unknown Source)
```

**Comment by HongSquare2** [comment]
Having this issue too. Anyone with any solutions?
Thanks.

**Comment by Manugal** [comment]
Same problem here. +1

**Comment by akexorcist** [comment]
@Hoosein I think it isn't related with ProGuard. It's some bug in my library that occurred in your production app accidentally. (It can be happen without ProGuard)

Please update to version 1.0.5 to fix this problem.

Thank you for your feedback

**Comment by Liverm0r** [comment]
I had the same problem with 1.0.4 after setting ProGuard.
1.0.5 didn't work with ProGuard either (except it didn't throw NullPointerException).

I fixed it by adding several lines in proguard-rules.pro file:

-keep class com.akexorcist.** { *; }
-keep interface com.akexorcist.** { *; }

-keep class com.google.android.gms.maps.** { *; }
-keep interface com.google.android.gms.maps.** { *; }
