### ISSUE TITLE
NPE on IsOk method in Direction class

### ISSUE THREAD

**Issue by nekooei** [akexorcist/Android-GoogleDirectionLibrary#23]
when i build release version of app app gives me this NPE
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.akexorcist.googledirection.model.Direction.isOK(Unknown Source)
       at taxi.shiraz.driver.map.MapBuilder$3.onDirectionSuccess(Unknown Source)
```

**Comment by akexorcist** [comment]
@nekooei I fixed it in version 1.0.5 

Thank you for your feedback
